[demo]
name = "demo"
output_dir = "./dist"
prompt = '\[\e[1;32m\]ghscaff@demo\[\e[0m\]:\[\e[1;34m\]~\[\e[0m\]$ '

[typing]
base_ms = 80
salt_ms = 15

[layout]
width = 810
height = 920
fps = 15
line_height = 1.2000000476837158
background = "#0b0f14"

[[layout.panes]]
id = "main"
type = "terminal"
x = 0
y = 0
width = 810
height = 920
font_family = "monospace"
font_size = 16

[[layout.panes]]
id = "scene1"
type = "browser"
x = 0
y = 0
width = 810
height = 920
url = "https://github.com/JheisonMB/demo-ghscaff"
theme = "dark"

[[timeline]]
action = "focus"
pane = "main"

[[timeline]]
action = "type"
text = "ghscaff"
human_salt = true

[[timeline]]
action = "wait"
duration_ms = 1287

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 2500

[[timeline]]
action = "secret"
prompt = "Vault passphrase:"

[[timeline]]
action = "type"
text = "demo-ghscaff"
human_salt = true

[[timeline]]
action = "wait"
duration_ms = 360

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 2304

[[timeline]]
action = "type"
text = "a demo repository"
human_salt = true

[[timeline]]
action = "wait"
duration_ms = 390

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1441

[[timeline]]
action = "type"
text = "demo,ghscaff,temp"
human_salt = true

[[timeline]]
action = "wait"
duration_ms = 2500

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1183

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1268

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1129

[[timeline]]
action = "keypress"
key = "down"

[[timeline]]
action = "wait"
duration_ms = 243

[[timeline]]
action = "keypress"
key = "down"

[[timeline]]
action = "wait"
duration_ms = 409

[[timeline]]
action = "keypress"
key = "up"

[[timeline]]
action = "wait"
duration_ms = 1542

[[timeline]]
action = "keypress"
key = "up"

[[timeline]]
action = "wait"
duration_ms = 406

[[timeline]]
action = "keypress"
key = "down"

[[timeline]]
action = "wait"
duration_ms = 155

[[timeline]]
action = "keypress"
key = "down"

[[timeline]]
action = "wait"
duration_ms = 332

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 2137

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1332

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1140

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 841

[[timeline]]
action = "keypress"
key = "down"

[[timeline]]
action = "wait"
duration_ms = 402

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 2500

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 2500

[[timeline]]
action = "type"
text = "n"
human_salt = true

[[timeline]]
action = "wait"
duration_ms = 508

[[timeline]]
action = "keypress"
key = "enter"

[[timeline]]
action = "wait"
duration_ms = 1500

[[timeline]]
action = "focus"
pane = "scene1"

[[timeline]]
action = "wait"
duration_ms = 4000

[[timeline]]
action = "terminate"
